# .github/workflows/deploy.yml
name: Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Prisma commands
      run: |
        npx prisma migrate reset --force
        npx prisma migrate dev --name init
        npx prisma generate
        npx prisma db push
    
    - name: Build
      run: npm run build
    
    - name: Start production
      run: npm run start:prod &
    
    - name: Deploy to Render
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}'
        method: 'POST'